### ISSUE TITLE
Simplify and improve critical path algorithm

### ISSUE THREAD

**Issue by maltezfaria** [maltezfaria/DataFlowTasks.jl#14]
We should avoid the creation of a dense adjacency matrix for doing this computation. Also, I think we could do something simpler than Djisktra here (see e.g. https://www.geeksforgeeks.org/find-longest-path-directed-acyclic-graph/)

_Originally posted by @maltezfaria in https://github.com/maltezfaria/DataFlowTasks.jl/pull/10#discussion_r907534675_

**Comment by maltezfaria** [comment]
This was closed too early. Turns out the *critical path* algorithm is still quite brittle. It assumes, for instance, that the tags for the tasks start at `1`, if that is not the case it errors with an out-of-bounds access. Probably a rewrite of the logger and graph algorithms is in order.

**Comment by ffevotte** [comment]
Agreed!
This might not be as straightforward as I initially thought, though: for example, how to know which task is the first one we want to log? Or even: is there necessarily a unique first task?
