### ISSUE TITLE
Decide where to put PseudoTiledMatrix

### ISSUE THREAD

**Issue by ffevotte** [maltezfaria/DataFlowTasks.jl#21]
A question that came up in today's meeting is where to put the definition of the `PseudoTiledMatrix` type

- it seems to be useful and general enough to apply to more than the Cholesky factorization example. Other examples from the documentation involve tiled linear algebra and can use this type
- the Cholesky factorization example given in the README could probably be rewritten in such a way as to depend only on `LinearAlgebra` and other standard libraries, except for its use of `PseudoTiledMatrix` (which must currently be imported from `TiledFactorization.jl` if one wants to actually run the code provided in the README)
- OTOH, it does not look like tiles matrices are strongly linked to DAG-based DataFlow parallelism, so that it's not really satisfactory to bundle both in the same package.

Maybe a middle ground could be to have a `PseudoTiledMatrix` implementation available in `DataFlowTasks` but "hidden", i.e. not part of the official API, and perhaps even separated in a submodule.

Anyways, any opinions on this are welcome!

**Comment by maltezfaria** [comment]
Moving it back to `DataFlowTasks` feels like going back on our decision to separate the **data flow logic** from the possible **applications**. Perhaps we can have an `extras.jl` file that does not get included in the package, but that we can manually include in the docs where needed? That will cause some code duplication, but the implementation of `PseudoTiledMatrix` is very simple, so IMO that is not an issue.

**Comment by ffevotte** [comment]
> Moving it back to DataFlowTasks feels like going back on our decision to separate the data flow logic from the possible applications.

Yes, I'm inclined to think so too.

<br/>

>  the implementation of PseudoTiledMatrix is very simple, so IMO that is not an issue.

Thinking more about this, I'm starting to think that `PseudoTiledMatrix` is so simple that basic examples could perhaps entirely get rid of it. Couldn't we for example have something along the lines of:
```julia
A = rand(100, 100)
bs = 10  # block size (assume it divides the matrix size)
Atile = [view(A, (i*bs+1):((i+1)*bs), (j*bs+1):((j+1)*bs)) for i in 0:(N÷bs-1), j in 0:(N÷bs-1)];
```

In terms of documentation/examples, this could have the added benefit that everyone can see that there is no magic in the way tiles are defined. And of course this is entirely self-contained

A full-fledged `PseudoTiledMatrix` can still be useful in `TiledFactorization.jl`.

**Comment by ffevotte** [comment]
OK, the consensus seems to be that examples in the `DataFlowTasks` documentation should be self contained, and not rely on `PseudoTiledMatrix`.
