### ISSUE TITLE
Tricky behavior with captured variables

### ISSUE THREAD

**Issue by ffevotte** [maltezfaria/DataFlowTasks.jl#25]
When trying to implement new examples with DataFlowTasks, I encountered the following situation, which I find very tricky and hard to understand.

The example below is not so minimal, but it is not huge either, and it does something useful (solving a constant-speed transport equation in 1D) which is always nice IMO:

```julia
using Plots
using DataFlowTasks

function timestep!(u_new, u_old, α)
    for i in 2:lastindex(u_old)
        u_new[i] = u_old[i] - α * (u_old[i] - u_old[i-1])
    end
end

function solve!(uₙ, u₀, n, α)
    @assert iseven(n)

    # Two workspaces
    uₖ = uₙ          # solution at current timestep (known)
    uₖ₊₁ = zero(uₙ)  # solution at next timestep (to be computed with the FD scheme)

    copy!(uₖ, u₀)
    for k in 1:n
        # uncomment the variables in the let-block below to fix the problem
        let #uₖ₊₁=uₖ₊₁, uₖ=uₖ
            @dspawn timestep!(@W(uₖ₊₁), @R(uₖ), α) label="iter $k"
        end

        # !!! THIS IS THE TRICKY PART !!!
        # Swap both vectors:
        # - the newly computed solution becomes the known one
        # - the last known timestep will be re-used for the next time step
        (uₖ, uₖ₊₁) = (uₖ₊₁, uₖ)
    end

    # if the number of time steps is even, the last timestep will be in uₙ
    # (otherwise, we'd need one final copy from the temporary array uₖ₊₁ into uₙ)
    res = @dspawn @R(uₙ) label="result"
    fetch(res)
end
```

And here are some data to test it:
```julia
# Test case
N = 1000        # number of spatial meshes
c = 0.8         # advection speed
h = 1 / (N-1)   # spatial step
Δt = h          # time step (respects the CFL condition if c ≤ 1)
α = c*Δt/h      # convenient parameter for the scheme

# initial solution
x = 0:h:1
u₀ = (1 .+ sinpi.(5x)) .* (0.3 .< x .< 0.7)

# solution after 4 time steps
uₙ = similar(u₀)
solve!(uₙ, u₀, 4, α)
@assert uₙ != u₀
```

As it stands, it looks like the DAG is correct (at least it always was in my tests), but the computation almost always ends up with uₙ == u₀, which means that it *looks like* no computation was actually performed in the spawned tasks.

This is because `@dspawn timestep!(uₖ₊₁, uₖ, α)` makes a closure that captures the variables `uₖ₊₁` and `uₖ`, which are local to the function (not the `for` loop). This means that swapping the variables (i.e. re-binding them differently) at the end of each iteration can (and will) affect the behavior of the closures.

Putting a `let` block around the task creation works around the problem by making sure that the closures capture variables that are purely local to the `let` block.

I wonder whether we shouldn't make `@dspawn` & friends generate such a `let`-block automatically, because (1) this could become quite hard to debug, and (2) writing such `let`-blocks by hand is very tedious.

**Comment by maltezfaria** [comment]
Just to add to this discussion, here a MWE at the level of the `Task`s themselves:

```julia
A = ones(5); B = zeros(5)
tw = @task nothing
ta = Threads.@spawn (wait(tw); A) # spawn but does not run yet
A,B = B,A # swap 
schedule(tw) # ta can now run, but A and B have been swapped 
fetch(ta) # returns zeros
```

This is not really a bug, but not a feature either 😆

**Comment by maltezfaria** [comment]
@ffevotte Any updates on this issue? It seems that it is "just" a matter of documenting the tricky behaviour. As the example I posted above illustrates, this tricky behaviour is also present in `Threads.@task` (or more general problems involving closures?). Maybe I could write up a `warning` admonition in the docs?

**Comment by ffevotte** [comment]
No specific update on this on my part, but yes: I agree that this is "just" a matter of warning users, and maybe advertising the classical `let`-based workaround.

I'm unsure about where to do this, though. I think a warning admonition in the docs would be a good start (and the only thing needed in the short term).

But an admonition will probably not give us enough space to say everything. IIRC, one of the half-baked  examples (possibly `stencil`) exhibits this, so maybe we could finish cleaning up that example and use it to talk in more depth about the issue.

**Comment by maltezfaria** [comment]
> But an admonition will probably not give us enough space to say everything. IIRC, one of the half-baked examples (possibly `stencil`) exhibits this, so maybe we could finish cleaning up that example and use it to talk in more depth about the issue.

👍 That would be much better, as we can explain the issue more throughly in an extended example. Also, a `warning` admonition at say the *getting started* portion may scare the faint hearted 🤣

**Comment by maltezfaria** [comment]
I am going to be busy today, but I could take up the stencil example over the next couple of days. Up to you.
