### ISSUE TITLE
Useless code invalidations with `enable_log()` & co

### ISSUE THREAD

**Issue by ffevotte** [maltezfaria/DataFlowTasks.jl#27]
The following behavior has caused some difficult-to-understand profiling results:
```julia
julia> using DataFlowTasks

julia> function foo(x)
           @dspawn @R(x)
       end
foo (generic function with 1 method)

julia> a = rand(10);

# This compiles => OK
julia> @time foo(a)
  0.335148 seconds (1.62 M allocations: 89.050 MiB, 5.17% gc time, 99.98% compilation time)
DataFlowTask (done) 1

# No compilation any more => OK
julia> @time foo(a)
  0.000031 seconds (29 allocations: 2.109 KiB)
DataFlowTask (done) 2

# This triggers a code invalidation
# => maybe necessary from a user's perspective because one might not know what the default log mode is or will be
julia> DataFlowTasks.enable_log()
true

# Code needs to be recompiled
julia> @time foo(a)
  0.047678 seconds (80.19 k allocations: 4.268 MiB, 99.89% compilation time)
DataFlowTask (runnable) 3

julia> @time foo(a)
  0.019107 seconds (118.42 k allocations: 6.647 MiB, 30.46% gc time, 99.59% compilation time)
DataFlowTask (done) 4

# This triggers a code invalidation again !
julia> DataFlowTasks.enable_log()
true

# Code needs to be recompiled (again)
julia> @time foo(a)
  0.045255 seconds (80.18 k allocations: 4.268 MiB, 99.91% compilation time)
DataFlowTask (runnable) 5

julia> @time foo(a)
  0.000061 seconds (28 allocations: 2.062 KiB)
DataFlowTask (done) 6
```

The same thing should happen with all "friends" of `enable_log`, such as `enable_debug` and `force_sequential` (we should make sure there are no others)

What we can do about it:
1. promote examples in the documentation, where `DataFlowTasks` is set up before we run the code to profile a first time to trigger compilation
2. change the implementation of `enable_log` & co so that code is invalidated only in cases where the `DataFlowTasks` settings have actually changed.

**Comment by maltezfaria** [comment]
> What we can do about it:
> 
> 1. promote examples in the documentation, where `DataFlowTasks` is set up before we run the code to profile a first time to trigger compilation
> 2. change the implementation of `enable_log` & co so that code is invalidated only in cases where the `DataFlowTasks` settings have actually changed.

Just in case you are still hesitant, I vote number 2 👍
