### ISSUE TITLE
Tests on `CI` take too long

### ISSUE THREAD

**Issue by maltezfaria** [maltezfaria/DataFlowTasks.jl#33]

**Comment by ffevotte** [comment]
Could we perhaps set things up in such a way that `TiledFactorization` tests run only every once in a while?

**Comment by maltezfaria** [comment]
That is a good idea. It should be possible to do that on the `CI` end by tweaking the `CI.yaml` file to only run the full suite of tests when e.g. we make a `PR` or tag a release.

**Comment by maltezfaria** [comment]
I think the runtime of the `TiledFactorization` tests are comparable to the other tests we run. So, although we could try to speed those up, for now it is not something major that is bothering me (takes about 15min to test everything on the `CI`). See e.g. this run:

https://github.com/maltezfaria/DataFlowTasks.jl/actions/runs/6659803775/job/18099660420

Closing this.
