### ISSUE TITLE
Document troubleshooting and debugging strategies

### ISSUE THREAD

**Issue by maltezfaria** [maltezfaria/DataFlowTasks.jl#40]
We should improve the documentation of how to debug `DataFlowTasks`. In particular, we should mention the `force_sequential` method as a first check. It turns out that a lot of the times the problem is with the serial code, and it is much easier to read the serial stack trace than the parallel one!

**Comment by maltezfaria** [comment]
Make sure to also mention `restart_scheduler!` (speaking from personal experience here 😅 )

**Comment by maltezfaria** [comment]
Ok, a few more hours implementing the hiearchical `LU` on `HMatrices.jl` using `DataFlowTasks`. It works now, but here are some lessons learned:
- *Debugging `DataFlowTasks` is hard*. The workflow I found most useful was:
    1. Write the serial code, make sure it work
    2. Add the `@dspawn` to the serial code
    3. Run the code with `force_sequential` and make sure it still works
    4. Run the code with a new `force_linear_dag()=true` (name to be discussed). This makes sure `DataFlowTask`s are created and schedule, but it forces the underlying `DAG` to be linear (i.e node `i` is always connected to node `i+1`. This is closer to the *real thing* than `force_sequential`, and was quite helpful as a debugging tool. One subtlety I encountered had to do with the behaviour of captured variables (#25), and step `iv` helps to debug this. 
    5. If `iv` works, then deactivate the `force_linear_dag()` and see if tests pass. If they don't, the problem is in the data dependencies. Look at the code, scratch your head, and continue debugging 😕 

- Things are tricky when a `DataFlowTask` creates data, and some subsequent tasks need to use it. For example:
```julia
t1 = @dspawn (sleep(1); ones(2))
t2 = @dspawn
    sum(fetch(t1))
end
```
Fetching `t2` will work, but the internal task graph does not know explicitly that `t2` depends on `t1`, so lots of the logging information obtained are misleading. In fact, it will log `t2` as taking roughly `1` second to run. Ideally, we would not start running the code in `t2` task until `t1` is finished, and for that there should be an edge `t1 --> t2`. Can we automatically add that in the example above? If not, how do we handle the case where **data is created** inside a task? One alternative is to do
```julia
t2 = @dspawn
    sum(fetch(@R(t1)))
end
```
which will add `t1` as a read dependency to `t2`. We then need to slightly change how dependencies are computed to treat the case where some of the `data` is itself a `DataFlowTask`. Seems a bit hacky...

- Composing `@dspawn`ed tasks does not work (i.e having a `@dspawn` task in the block of another `@dspawn` task). There is a conceptual problem with allowing for that to happen, which is that now the order is no longer *unique*, but does it make sense to support that (assuming the user know what they are doing and in those cases the order does not really matter)?

**Comment by ffevotte** [comment]
What part of this do we want to address for the v0.2 release?

The options I see would be
1. do nothing more than what we currently have, and postpone most of this to v0.3
2. take advantage of the newly created "Troubleshooting" documentation page, and add there a description of the workflow given above
3. address the underlying issues of tasks-creating-data and tasks-within-tasks

I think we already decided against option 3, but I'm not sure about 1 or 2.

**Comment by maltezfaria** [comment]
Lazy me wants to go with `1`, but I think now is the time to improve the *Troubleshooting* section and write two new subsections:
- Nested spawning of `DataFlowTask`s (and related issues)
- Suggested workflow (mention `force_sequential` and `force_linear_dag`)

I can take care of this.
