### ISSUE TITLE
Towards v0.2.0

### ISSUE THREAD

**Issue by ffevotte** [maltezfaria/DataFlowTasks.jl#43]
Here are IMO a few things that we may want to tackle before tagging a v0.2.0 release. Maybe listing them all together here will help prioritize things:

- [x] #40 
- [x] #42
- [x] #44
- [x] #45
- [x] #47
- [x] #53
- [x] #48
- [x] #49 
- [x] #39 (improved in #64)
- [x] #68 
- [x] #25 

To be completed / discussed / pruned

**Comment by maltezfaria** [comment]
I am appending some more items to your list above. We don't have to tackle them all, just thought it would be good to jot them down somewhere.

**Comment by ffevotte** [comment]
Regarding the topic of dependency management in the docs subproject, there seem to be 3 possibilities:

1. `docs/Project.toml` does not refer to `DataFlowTasks` and we rely on the CI setup to `Pkg.dev` it at the right time.
    - that's what we did until now; it served us well
    - it's slightly harder to make local documentation builds: you need to locally `Pkg.dev` the current project and then revert the changes before committing to git
2. `docs/Project.toml` refers to `DataFlowTasks` but we don't commit the `Manifest.toml` alongside it => we still rely on the CI setup to `Pkg.dev` the parent project before building the doc
    - this make the local `Project.toml` consistent with what's committed on git
3. `docs/Project.toml` and `docs/Manifest.toml` are both committed to git and refer to `DataFlowTasks` as a dev-ed package with relative path `..`
    - I would be slightly worried about the committed `docs/Manifest.toml` getting out-of-date, but
    - this seems to be the recommended way of doing things nowadays; at least that is how recent versions of `PkgTemplates` set up new projects


All in all, I would favor options (2) or (3), but as I said in #42, I'm open to compromises on this topic :smiley:

**Comment by maltezfaria** [comment]
In my experience, `Manifest.toml`s are difficult to keep up to date, and eventually, I forget to commit changes to the `Manifest`. Having it tracked by `git` also creates many *artificial* conflicts when rebasing, merging, etc. Given that, I prefer option 2, which seems like a good compromise between a fully reproducible environment (with more info than what we care about most of the time) and completely relying on the CI to set up things properly (option 1).

**Comment by maltezfaria** [comment]
If you have not done so already, I am gonna tackle the `Aqua.jl` issue next.

**Comment by ffevotte** [comment]
> Given that, I prefer option 2, which seems like a good compromise

Agreed! I'm on it!

EDIT: it's actually already set up like this since #42, sorry for the noise!

**Comment by maltezfaria** [comment]
I have added another issue in #49 that I think is interesting. Maybe it does not belong to `0.2` though?

**Comment by maltezfaria** [comment]
#49 is being tackled in #52. I am more or less happy with the outcome, but it needs to be reviewed as it changes a bit of the internal structure, as well as the API (it simplifies it IMO).
