### ISSUE TITLE
Ensure proper formatting with `JuliaFormatter.jl`

### ISSUE THREAD

**Issue by ffevotte** [maltezfaria/DataFlowTasks.jl#48]
Decide on a format, and use `JuliaFormatter.jl` to automatically format the code. Add a `CI` action to check the format.

- [JuliaFormatter documentation](https://domluna.github.io/JuliaFormatter.jl/stable/)
- [JuliaFormatter GitHub actions](https://github.com/julia-actions/julia-format)

**Comment by maltezfaria** [comment]
Some options:

- [`YAS`](https://github.com/jrevels/YASGuide)
- [`Blue`](https://github.com/invenia/BlueStyle) 
- [`SciML`](https://github.com/SciML/SciMLStyle)
-  A custom format

I don't really have a strong opinion on this. Any preferences?

**Comment by ffevotte** [comment]
There is also the Default style coming out-of-the-box with `JuliaFormatter`.

AFAIU from the documentation, `Blue` and `SciML`  styles are WIP, so I'd perhaps stick with the Default or YAS styles. I tried them locally and although both had a few quirks, I had a slight preference for YAS.

That being said, I don't have a strong opinion on this either. I'm not even really convinced we need this at this stage (although it probably does not hurt). Please feel free to decide whatever you like on this.

**Comment by maltezfaria** [comment]
I am pretty sure we don't need it, but I figured it would be nice to try it out. We can remove it later if it turns out that keeping the files formatted turns out to be a nuisance. I will implement this one then.

**Comment by maltezfaria** [comment]
Done in #50
