### ISSUE TITLE
API change / simplify internals of `DataFlowTasks`?

### ISSUE THREAD

**Issue by maltezfaria** [maltezfaria/DataFlowTasks.jl#49]
I have started to wonder if we need the `DataFlowTask` type at all. It would be nice if all we did was run some pre- and post-hook when a `Task` is created in order to keep track of data info (possibly in a global variable) and add some `wait`s depending on data dependencies. We will most likely still need a DAG-like to compute dependencies, but that is easy.

This would simplify the package's logic, and make it very clear that the sole role played by `DataFlowTask` is to automatically add some synchronization between tasks based on data. I am not sure whether this is possible to do in practice. Can we, for instance, simply overload the `Task` constructor?

```julia
function Task(func;data,mode)
        # compute dependencies using some global DAG
        deps  = compute_deps(data,mode) 
        # create the task
        tj = @task do
           # append dependencies
           for ti in deps
              wait(ti)
           end
           # run user's code
           res = func() 
           # post-hook, move itself to a finished Channel so that it can be removed from the global DAG
           add_to_finished!(tj)
           res
        end
        # add the task to the global DAG
        add_to_dag!(tj) 
        return tj
end
```

We would then need to adapt the macros accordingly, but if that is possible we would have a syntax like:

```julia
using DataFlowTasks
A = Vector{Float64}(undef, 4)
result = let
    @spawn fill!(@W(A), 0)           # task 1: accesses everything
    @spawn @RW(view(A, 1:2)) .+= 2   # task 2: modifies the first half
    @spawn @RW(view(A, 3:4)) .+= 3   # task 3: modifies the second half
    @spawn @R(A)                     # task 4: get the result
end
fetch(result)
```

Where we create `Task` objects, and not `DataFlowTask` objects.

Any thoughts?

**Comment by maltezfaria** [comment]
I think this can be done in two stages:

1. An `API` change: `DataFlowTask` is removed from the `API` (together with `@dspawn`). The usage is then solely through the `@R`, `@W` and `@RW` macros.
    - Overload `Task(f;data,mode)` and the associated macros `@spawn`, `@task`, etc. 
    - Do not change the internals (i.e. we still rely on `DataFlowTask` and current machinery to track data dependencies).  
    - Update the docs to emphasize the *add-on* nature of this package, which simply tags regular `Task`s with some data info. 

2. Simplify the internals
    - Remove the other schedulers
    - Simplify the `DAG` and related features

Point `1` could be a `0.2.0` objective, whereas `2` can be postponed to a later date (it won't break the `API`).

**Comment by ffevotte** [comment]
> Can we, for instance, simply overload the Task constructor?

Isn't this type piracy? Or would we shadow `Base.Task` with `DataFlowTasks.Task`?

**Comment by maltezfaria** [comment]
> > Can we, for instance, simply overload the Task constructor?
> 
> Isn't this type piracy? Or would we shadow `Base.Task` with `DataFlowTasks.Task`?

Not if we do `Task(func,data,mode::NTuple{N,AccessMode})` right? 

`AccessMode` is defined in `DataFlowTasks`. 

(Maybe this needs to be tweaked a bit to avoid the empty tuple case, in which case it may indeed be type piracy 🤔 )

**Comment by maltezfaria** [comment]
I just thought it would be nice if one could still use the standard syntax from `Base` and simply add `@R, @W, @RW` to it! Imagine writing the docs to explain how to use the package: one paragraph would suffice 🎉 

But if you think this is not (easily) doable, or too far-fetched, I will go ahead and close it.

**Comment by ffevotte** [comment]
Ah, this would be very nice indeed! 

> But if you think this is not (easily) doable, or too far-fetched, I will go ahead and close it.

I don't see right now how we could achieve something like this, but let's think about it some more before we deem it undoable!

**Comment by maltezfaria** [comment]
I don't see how to achieve what I described for the `@spawn` macro without committing some sort of type piracy 😞

I agree, let's sit on this for a while longer before giving up.
