### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by JieRen98** [maltezfaria/DataFlowTasks.jl#54]
```Julia
using DataFlowTasks
A = Vector{Float64}(undef, 4)
result = let
    @dspawn fill!(@W(A), 0)           # task 1: accesses everything
    @dspawn @RW(view(A, 1:2)) .+= 2   # task 2: modifies the first half
    @dspawn @RW(view(A, 3:4)) .+= 3   # task 3: modifies the second half
    @dspawn @R(A)                     # task 4: get the result
end
fetch(result)

log_info = DataFlowTasks.@log let
    @dspawn fill!(@W(A), 0)             label="write whole"
    @dspawn @RW(view(A, 1:2)) .+= 2     label="write 1:2"
    @dspawn @RW(view(A, 3:4)) .+= 3     label="write 3:4"
    res = @dspawn @R(A)                 label="read whole"
    fetch(res)
end

DataFlowTasks.stack_weakdeps_env!() # Set up a stacked environment so that weak dependencies such as GraphViz can be loaded. More about that hereafter.
using GraphViz # triggers additional code loading, powered by weak dependencies (julia >= 1.9)
dag = GraphViz.Graph(log_info)
```

Env: Ubuntu 22.04, Julia 1.9.3

Program stuck

**Comment by maltezfaria** [comment]
Is it the `DataFlowTasks.stack_weakdeps_env!()` that seems to hang for you? Did you try 
```julia
DataFlowTasks.stack_weakdeps_env!(;verbose=true)
```
to make sure it is not doing something (possibly installing `Makie` and other heavy plotting dependencies)?

**Comment by maltezfaria** [comment]
Assuming that is the case... and all that you need is to plot the `DAG` using `GraphViz`, you could add just `GraphViz` to your current environment (instead of using `stack_weakdeps_env!`).

**Comment by JieRen98** [comment]
It worked smoothly, it was compiling things. Thank you!

**Comment by maltezfaria** [comment]
Great! It should only be (super) slow the first time around by the way.

**Comment by JieRen98** [comment]
DFT helps a lot. I have tried Dagger and builtin functions (spawn and fetch
for guaranteeing task dependencies) for multi threading acceleration of
some linear algebra applications. It seems that so far DFT gives the best
performance. Could you please give some hints for why DFT outperforms them?

Luiz M. Faria ***@***.***>于2023年9月27日 周三12:45写道：

**Comment by maltezfaria** [comment]
If you have a linear algebra problem where DFT is working well, it would be great to add it to the examples in the docs!

As for the speed, it should not be faster than the builtin functions (it uses those internally). Where DFT is hopefully useful is to declare complex tasks interdependencies stemming from data reuse. If your algorithm is simple enough and you can manually say which task depends on which task (using e.g. `wait` or `fetch`), then the whole data-flow analysis is not necessary.

**Comment by JieRen98** [comment]
Yes, I will later.
